version: 2
updates:
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: daily    # Value can be : daily, weekly, monthly
      time: "12:38"
    open-pull-requests-limit: 10     # Maximum 10 PR at a time
    commit-message:
      prefix: "mvn"
    ignore:
      - dependency-name: "org.seleniumhq.selenium:selenium-java"
        versions: ["4.x"]
      - dependency-name: "io.github.bonigarcia:webdrivermanager"
      - dependency-name: "io.appium:java-client"
        update-types: ["version-update:semver-minor"]
      - dependency-name: "com.google.guava:guava"
    reviewers:
      - "Mandeepsheoran"
