name: run ios tests

on: 
 push:
  branches: main
 workflow_dispatch:
 
jobs:
  run-ios-tests:
    runs-on: macos-latest

    steps:
      - name: setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: pull the project in to the runner
        uses: actions/checkout@v3

      - name: setup appium
        run: |
          npm install -g appium@v1.22
          appium -v
          appium &>/dev/null &

      - name: run appium ios tests
        run: mvn clean test -Pios-testng
