name: Web test in Selenoid with caching

on:
 workflow_dispatch:

jobs:
 build:
  name: run web test in Selenoid
  runs-on: ubuntu-latest

  steps:
    - name: Pull code from workspace to the runner
      if: github.actor == 'Mandeepsheoran'
      uses: actions/checkout@v2
      timeout-minutes: 10

    - name: Setup Java 17
      uses: actions/setup-java@v1
      timeout-minutes: 10
      with:
          java-version: 17
          
    - name: store docker image cache
      uses: satackey/action-docker-layer-caching@v0.0.11
      continue-on-error: true       

    - name: Start Selenoid server
      uses: n-ton4/selenoid-github-action@master
      id: start-selenoid
      continue-on-error: false
      with:
          version: 1.10.1
          args: -limit 10
          browsers: chrome
          last-versions: 1      

    - name: Restore Maven cache
      uses: skjolber/maven-cache-github-action@v1
      continue-on-error: true
      with:
         step: restore  

    - name: Run test with Maven
      timeout-minutes: 10
      run: |
         mvn -v 
         mvn clean install -Pselenium-testng
         
    - name: Save Maven cache
      uses: skjolber/maven-cache-github-action@v1
      continue-on-error: true
      with:
         step: save
