name: Web test in Selenoid

on:
 push:
  branches: main
 workflow_dispatch:

jobs:
 build:
  name: run web test in Selenoid
  runs-on: ubuntu-latest

  steps:
    - name: Pull code from workspace to the runner
      if: github.actor == 'Mandeepsheoran'
      uses: actions/checkout@v2
      timeout-minutes: 10

    - name: Setup Java 17
      uses: actions/setup-java@v1
      timeout-minutes: 10
      with:
          java-version: 17

    - name: Start Selenoid server
      uses: n-ton4/selenoid-github-action@master
      id: start-selenoid
      continue-on-error: false
      with:
          version: 1.10.1
          args: -limit 10
          browsers: chrome
          last-versions: 1      

    - name: Run test with Maven
      timeout-minutes: 10
      run: |
         mvn -v 
         mvn clean install -Pselenoid-testng
