name: Web test

on:
 push:
  branches: main
 workflow_dispatch:

jobs:
 build:
  name: run web test
  runs-on: windows-latest

  steps:
    - name: Pull code from workspace to the runner
      if: github.actor == 'Mandeepsheoran'
      uses: actions/checkout@v2
      timeout-minutes: 10

    - name: Setup Java 17
      uses: actions/setup-java@v1
      timeout-minutes: 10
      with:
          java-version: 17

    - name: Run test with Maven
      timeout-minutes: 10
      run: |
         mvn -v 
         mvn clean install -Pweb-testng
  
 
